image: hashicorp/terraform:1.5.0

stages:
  - validate
  - plan
  - apply

before_script:
  - terraform --version

validate:
  stage: validate
  script:
    - terraform init -backend=false
    - terraform validate
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

plan:
  stage: plan
  script:
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

apply:
  stage: apply
  script:
    - terraform init
    - terraform apply -auto-approve tfplan
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'